export const metadata = { title: "RoadStation privacy", description: "How the RoadStation iPhone app handles imported projects, phone location, MapKit, support messages, and device backups.", alternates: { canonical: "https://vericivil.com/roadstation/privacy" } };
export default function Page() { return <article className="legal-document roadstation-legal">
  <header><h1>Privacy policy</h1><span>Effective October 7, 2026</span></header>
  <p>This policy covers the RoadStation iPhone app, provided by Cole Winstead. The VeriCivil website has its own <a href="/privacy">website privacy policy</a>.</p>
  <section><h2>Your projects stay on your device</h2><p>RoadStation copies imported LandXML files into its app storage and saves project metadata, CRS selections and alignment selections on your device. The app does not upload these files to the developer. It has no developer-operated backend, accounts, analytics or advertising SDKs.</p></section>
  <section><h2>Location</h2><p>With your permission, the app processes phone location temporarily to calculate horizontal station and offset and display positioning quality. Location is used only while Field Position is active and the app is active. Live fixes and query histories are not persisted. Location is not sent to the developer. You can deny or change permission in iOS Settings and still use manual inspection.</p></section>
  <section><h2>Apple Maps & system services</h2><p>Geographic maps use Apple MapKit. Map requests may transmit map-area and other service information to Apple under <a href="https://www.apple.com/legal/privacy/">Apple’s privacy policy</a>. Apple’s operating-system services and optional diagnostics are separate from data collection by RoadStation’s developer. Offline Engineering View does not need map imagery.</p></section>
  <section><h2>Deletion & backups</h2><p>Delete a project in RoadStation to remove its app-owned file and metadata. This does not remove the original document in Files or copies held elsewhere. App storage may be included in device or iCloud backups according to your system settings; RoadStation does not exclude projects from system backup. Removing the app and managing backups are separate iOS operations. Previously created backups may retain copies.</p></section>
  <section><h2>Support & external links</h2><p>Opening a website or email link uses the selected external service. If you email support, we receive the address, message and attachments you choose to send and use them to answer your request. Avoid sending confidential project files or exact location unless necessary. Website hosting and email providers may process those communications separately from the app.</p></section>
  <section><h2>Questions & changes</h2><p>Contact <a href="mailto:support@vericivil.com">support@vericivil.com</a>. Changes to the app’s data handling will be reflected here before the affected release.</p></section>
</article>; }
